// set some name and values into local storage....

localStorage.setItem('name', 'Abhi');
localStorage.setItem('name2', 'Dev');

// see this data on chrome application local storage...

// clear local storage...
// localStorage.clear();

// remove any perticular item like name2...
localStorage.removeItem('name2');

// if want to use local storage key-value...
let myName = localStorage.getItem('name');
console.log(myName);

// if i want to add some data types like array then...

let myArr = [2, 'varun', null];
localStorage.setItem('Array', myArr);
// but its store in string so....

// use this some functions...
localStorage.setItem('Array', JSON.stringify(myArr));

// now i want to access this array then....
let name = localStorage.getItem('Array');
console.log(name); // but its a string

// so,

// now the actully use of json.parse....
name = JSON.parse(localStorage.getItem('Array'));
console.log(name);

// it means...
// JSON.stringify => store proper data type in local storage like array, object etc...
// JSON.parse => use data from local storage as before data type like above...